version: '3'

services:
    zookeeper:
        image: bitnami/zookeeper:latest
        networks:
            - app-tier
        ports:
            - '2181:2181'
        environment:
            - ZOO_SERVER_ID=1
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: bitnami/kafka:latest
        networks:
            - app-tier
        depends_on:
            - zookeeper
        ports:
            - '9093:9093'
            - '9092:9092'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092, EXTERNAL://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092, EXTERNAL://localhost:9093
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        networks:
            - app-tier
        depends_on:
            - kafka
        ports:
            - 9000:9000
        environment:
            - KAFKA_BROKERCONNECT=kafka:9092

networks:
    app-tier:
        driver: bridge
